using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Microkernel.RpcGenerator.Generators
{
    public static class ClientProxyGenerator
    {
        public static string Generate(INamedTypeSymbol interfaceSymbol, List<(IMethodSymbol Method, uint MethodId)> methods)
        {
            string ns = interfaceSymbol.ContainingNamespace.IsGlobalNamespace
                ? ""
                : interfaceSymbol.ContainingNamespace.ToDisplayString();

            string interfaceName = interfaceSymbol.Name;
            string clientName = interfaceName.StartsWith("I") && interfaceName.Length > 1
                ? interfaceName.Substring(1) + "Client"
                : interfaceName + "Client";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using Userland.Runtime.ZeroAlloc.Interop;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("namespace " + ns);
                sb.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.AppendLine(indent + "public unsafe struct " + clientName + " : " + interfaceName);
            sb.AppendLine(indent + "{");
            sb.AppendLine(indent + "    private readonly uint _endpointCptr;");
            sb.AppendLine();
            sb.AppendLine(indent + "    public " + clientName + "(uint endpointCptr)");
            sb.AppendLine(indent + "    {");
            sb.AppendLine(indent + "        _endpointCptr = endpointCptr;");
            sb.AppendLine(indent + "    }");
            sb.AppendLine();

            foreach (var item in methods)
            {
                IMethodSymbol m = item.Method;
                uint methodId = item.MethodId;

                string retType = m.ReturnType.ToDisplayString();
                var paramDefs = new List<string>();
                for (int i = 0; i < m.Parameters.Length; i++)
                {
                    IParameterSymbol p = m.Parameters[i];
                    paramDefs.Add(p.Type.ToDisplayString() + " " + p.Name);
                }

                sb.AppendLine(indent + "    public " + retType + " " + m.Name + "(" + string.Join(", ", paramDefs.ToArray()) + ")");
                sb.AppendLine(indent + "    {");

                string d0 = m.Parameters.Length > 0 ? "(ulong)" + m.Parameters[0].Name : "0UL";
                string d1 = m.Parameters.Length > 1 ? "(ulong)" + m.Parameters[1].Name : "0UL";
                string d2 = m.Parameters.Length > 2 ? "(ulong)" + m.Parameters[2].Name : "0UL";
                string d3 = m.Parameters.Length > 3 ? "(ulong)" + m.Parameters[3].Name : "0UL";

                sb.AppendLine(indent + "        ulong msgInfo = " + methodId + "UL;");
                sb.AppendLine(indent + "        ulong ret = SyscallWrappers.Call(_endpointCptr, msgInfo, " + d0 + ", " + d1 + ", " + d2 + ", " + d3 + ");");

                if (retType != "void")
                {
                    sb.AppendLine(indent + "        return (" + retType + ")ret;");
                }

                sb.AppendLine(indent + "    }");
                sb.AppendLine();
            }

            sb.AppendLine(indent + "}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }
    }
}
