using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Microkernel.RpcGenerator.Generators
{
    public static class ServerDispatcherGenerator
    {
        public static string Generate(INamedTypeSymbol interfaceSymbol, List<(IMethodSymbol Method, uint MethodId)> methods)
        {
            string ns = interfaceSymbol.ContainingNamespace.IsGlobalNamespace
                ? ""
                : interfaceSymbol.ContainingNamespace.ToDisplayString();

            string interfaceName = interfaceSymbol.Name;
            string dispatcherName = interfaceName.StartsWith("I") && interfaceName.Length > 1
                ? interfaceName.Substring(1) + "Dispatcher"
                : interfaceName + "Dispatcher";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using Userland.Runtime.ZeroAlloc.Interop;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("namespace " + ns);
                sb.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.AppendLine(indent + "public static unsafe class " + dispatcherName);
            sb.AppendLine(indent + "{");

            // Generic devirtualized overload for structs
            sb.AppendLine(indent + "    public static void DispatchOnce<T>(ref T service, uint endpointCptr) where T : struct, " + interfaceName);
            sb.AppendLine(indent + "    {");
            sb.AppendLine(indent + "        ulong msgInfo, d0, d1, d2, d3;");
            sb.AppendLine(indent + "        ulong status = SyscallWrappers.Recv(endpointCptr, out msgInfo, out d0, out d1, out d2, out d3);");
            sb.AppendLine(indent + "        if (status != 0) return;");
            sb.AppendLine();
            sb.AppendLine(indent + "        uint methodId = (uint)(msgInfo & 0xFFFFFFFFUL);");
            sb.AppendLine(indent + "        switch (methodId)");
            sb.AppendLine(indent + "        {");

            foreach (var item in methods)
            {
                IMethodSymbol m = item.Method;
                uint methodId = item.MethodId;

                sb.AppendLine(indent + "            case " + methodId + ":");
                sb.AppendLine(indent + "            {");

                var callArgs = new List<string>();
                string[] regNames = new[] { "d0", "d1", "d2", "d3" };
                for (int i = 0; i < m.Parameters.Length; i++)
                {
                    string pType = m.Parameters[i].Type.ToDisplayString();
                    string reg = (i < regNames.Length) ? regNames[i] : "0UL";
                    callArgs.Add("(" + pType + ")" + reg);
                }

                string callExpr = "service." + m.Name + "(" + string.Join(", ", callArgs.ToArray()) + ")";

                if (m.ReturnType.ToDisplayString() != "void")
                {
                    sb.AppendLine(indent + "                ulong result = (ulong)" + callExpr + ";");
                    sb.AppendLine(indent + "                SyscallWrappers.Reply(result, 0, 0, 0);");
                }
                else
                {
                    sb.AppendLine(indent + "                " + callExpr + ";");
                    sb.AppendLine(indent + "                SyscallWrappers.Reply(0, 0, 0, 0);");
                }

                sb.AppendLine(indent + "                break;");
                sb.AppendLine(indent + "            }");
            }

            sb.AppendLine(indent + "            default:");
            sb.AppendLine(indent + "                SyscallWrappers.Reply(0xFFFFFFFFFFFFFFFFUL, 0, 0, 0);");
            sb.AppendLine(indent + "                break;");
            sb.AppendLine(indent + "        }");
            sb.AppendLine(indent + "    }");
            sb.AppendLine();

            sb.AppendLine(indent + "    public static void Run<T>(ref T service, uint endpointCptr, ref bool running) where T : struct, " + interfaceName);
            sb.AppendLine(indent + "    {");
            sb.AppendLine(indent + "        while (running)");
            sb.AppendLine(indent + "        {");
            sb.AppendLine(indent + "            DispatchOnce(ref service, endpointCptr);");
            sb.AppendLine(indent + "        }");
            sb.AppendLine(indent + "    }");
            sb.AppendLine("}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }
    }
}
