<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../build/config/Driver.props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>pci_server</AssemblyName>
    <RootNamespace>PciServer</RootNamespace>
    <NoStdLib>true</NoStdLib>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../common/MiniCoreLib/MiniCoreLib.csproj" />
    <ProjectReference Include="../../common/Microkernel.Abstractions/Microkernel.Abstractions.csproj" />
    <ProjectReference Include="../../runtime/Userland.Runtime.ZeroAlloc/Userland.Runtime.ZeroAlloc.csproj" />
    <ProjectReference Include="../../compiler-plugins/Microkernel.RpcGenerator/Microkernel.RpcGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
