<Project>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoStdLib>false</NoStdLib>
    <NoConfig>false</NoConfig>
    <DisableImplicitFrameworkReferences>false</DisableImplicitFrameworkReferences>
    <GenerateTargetFrameworkAttribute>true</GenerateTargetFrameworkAttribute>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
