<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../build/config/Common.props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Microkernel.Drawing</AssemblyName>
    <RootNamespace>Microkernel.Drawing</RootNamespace>
    <NoStdLib>true</NoStdLib>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../common/MiniCoreLib/MiniCoreLib.csproj" />
  </ItemGroup>
</Project>
